export const flexLevelConfigs = {
  1: {
    instructions:
      "Use justify-content to move fruits to the end of the container!",
    basketCSS: {
      display: "flex",
      justifyContent: "flex-end",
      gap: "1rem",
      width: "100%",
    },
    fruitCSS: {
      display: "flex",
      justifyContent: "flex-start",
      alignItems: "flex-start",
      gap: "1rem",
      height: "200px",
      width: "100%",
    },
    missingProps: ["justify-content:flex-end"],
    maxLines: 1,
    acceptedAnswers: [
      "justify-content: flex-end;",
      "justify-content:flex-end;",
      "justify-content: flex-end",
      "justify-content:flex-end",
    ],
    fruits: [{ type: "apple" }],
    baskets: [{ type: "red" }],
    containerLayout: "simple",
    cssTarget: "container",
  },
  2: {
    instructions: "Use justify-content to center fruits in the container!",
    basketCSS: {
      display: "flex",
      justifyContent: "center",
      gap: "1rem",
      width: "100%",
    },
    fruitCSS: {
      display: "flex",
      gap: "1rem",
      width: "100%",
    },
    missingProps: ["justify-content:center"],
    maxLines: 1,
    acceptedAnswers: [
      "justify-content: center;",
      "justify-content:center;",
      "justify-content: center",
      "justify-content:center",
    ],
    fruits: [{ type: "apple" }, { type: "banana" }],
    baskets: [{ type: "red" }, { type: "yellow" }],
    containerLayout: "simple",
    cssTarget: "container",
  },
  3: {
    instructions:
      "Use justify-content to distribute fruits with space around them!",
    basketCSS: {
      display: "flex",
      justifyContent: "space-around",
      gap: "1rem",
      width: "100%",
    },
    fruitCSS: {
      display: "flex",
      gap: "1rem",
      width: "100%",
    },
    missingProps: ["justify-content:space-around"],
    maxLines: 1,
    acceptedAnswers: [
      "justify-content: space-around;",
      "justify-content:space-around;",
      "justify-content: space-around",
      "justify-content:space-around",
    ],
    fruits: [{ type: "apple" }, { type: "banana" }, { type: "grapes" }],
    baskets: [{ type: "red" }, { type: "yellow" }, { type: "violet" }],
    containerLayout: "simple",
    cssTarget: "container",
  },
  4: {
    instructions:
      "Use justify-content to distribute fruits with space between them!",
    basketCSS: {
      display: "flex",
      justifyContent: "space-between",
      gap: "1rem",
      width: "100%",
    },
    fruitCSS: {
      display: "flex",
      gap: "1rem",
      width: "100%",
    },
    missingProps: ["justify-content:space-between"],
    maxLines: 1,
    acceptedAnswers: [
      "justify-content: space-between;",
      "justify-content:space-between;",
      "justify-content: space-between",
      "justify-content:space-between",
    ],
    fruits: [
      { type: "apple", initialPosition: 1, correctPosition: 1 },
      { type: "banana", initialPosition: 2, correctPosition: 2 },
      { type: "grapes", initialPosition: 3, correctPosition: 3 },
    ],
    baskets: [
      { type: "red", position: 1 },
      { type: "yellow", position: 2 },
      { type: "violet", position: 3 },
    ],
    containerLayout: "simple",
    cssTarget: "container",
  },
  5: {
    instructions: "Use align-items to move fruits to the end vertically!",
    basketCSS: {
      display: "flex",
      alignItems: "flex-end",
      gap: "1rem",
      height: "100%",
      width: "100%",
    },
    fruitCSS: {
      display: "flex",
      gap: "1rem",
      height: "100%",
      width: "100%",
    },
    missingProps: ["align-items:flex-end"],
    maxLines: 1,
    acceptedAnswers: [
      "align-items: flex-end;",
      "align-items:flex-end;",
      "align-items: flex-end",
      "align-items:flex-end",
    ],
    fruits: [
      { type: "apple", initialPosition: 1, correctPosition: 1 },
      { type: "banana", initialPosition: 2, correctPosition: 2 },
      { type: "grapes", initialPosition: 3, correctPosition: 3 },
    ],
    baskets: [
      { type: "red", position: 1 },
      { type: "yellow", position: 2 },
      { type: "violet", position: 3 },
    ],
    containerLayout: "simple",
    cssTarget: "container",
  },
  6: {
    instructions: "Center fruits both horizontally and vertically!",
    basketCSS: {
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      gap: "1rem",
      height: "100%",
      width: "100%",
    },
    fruitCSS: {
      display: "flex",
      gap: "1rem",
      height: "100%",
      width: "100%",
    },
    missingProps: ["justify-content:center", "align-items:center"],
    maxLines: 2,
    acceptedAnswers: [
      "justify-content: center;\nalign-items: center;",
      "justify-content:center;\nalign-items:center;",
      "justify-content: center; align-items: center;",
      "justify-content:center; align-items:center;",
      "align-items: center;\njustify-content: center;",
      "align-items:center;\njustify-content:center;",
      "align-items: center; justify-content: center;",
      "align-items:center; justify-content:center;",
    ],
    fruits: [
      { type: "apple", initialPosition: 1, correctPosition: 1 },
      { type: "banana", initialPosition: 2, correctPosition: 2 },
      { type: "grapes", initialPosition: 3, correctPosition: 3 },
    ],
    baskets: [
      { type: "red", position: 1 },
      { type: "yellow", position: 2 },
      { type: "violet", position: 3 },
    ],
    containerLayout: "simple",
    cssTarget: "container",
  },
  7: {
    instructions: "Distribute fruits with space around and align to bottom!",
    basketCSS: {
      display: "flex",
      justifyContent: "space-around",
      alignItems: "flex-end",
      gap: "1rem",
      height: "100%",
      width: "100%",
    },
    fruitCSS: {
      display: "flex",
      gap: "1rem",
      height: "100%",
      width: "100%",
    },
    missingProps: ["justify-content:space-around", "align-items:flex-end"],
    maxLines: 2,
    acceptedAnswers: [
      "justify-content: space-around;\nalign-items: flex-end;",
      "justify-content:space-around;\nalign-items:flex-end;",
      "justify-content: space-around; align-items: flex-end;",
      "justify-content:space-around; align-items:flex-end;",
      "align-items: flex-end;\njustify-content: space-around;",
      "align-items:flex-end;\njustify-content:space-around;",
      "align-items: flex-end; justify-content: space-around;",
      "align-items:flex-end; justify-content:space-around;",
    ],
    fruits: [
      { type: "apple", initialPosition: 1, correctPosition: 1 },
      { type: "banana", initialPosition: 2, correctPosition: 2 },
      { type: "grapes", initialPosition: 3, correctPosition: 3 },
    ],
    baskets: [
      { type: "red", position: 1 },
      { type: "yellow", position: 2 },
      { type: "violet", position: 3 },
    ],
    containerLayout: "simple",
    cssTarget: "container",
  },
  8: {
    instructions: "Reverse the direction of fruits using flex-direction!",
    basketCSS: {
      display: "flex",
      flexDirection: "row-reverse",
      gap: "1rem",
      width: "100%",
    },
    fruitCSS: {
      display: "flex",
      gap: "1rem",
      width: "100%",
    },
    missingProps: ["flex-direction:row-reverse"],
    maxLines: 1,
    acceptedAnswers: [
      "flex-direction: row-reverse;",
      "flex-direction:row-reverse;",
      "flex-direction: row-reverse",
      "flex-direction:row-reverse",
    ],
    fruits: [
      { type: "apple", initialPosition: 1, correctPosition: 3 },
      { type: "banana", initialPosition: 2, correctPosition: 2 },
      { type: "grapes", initialPosition: 3, correctPosition: 1 },
    ],
    baskets: [
      { type: "red", position: 3 },
      { type: "yellow", position: 2 },
      { type: "violet", position: 1 },
    ],
    containerLayout: "simple",
    cssTarget: "container",
  },
  9: {
    instructions: "Stack fruits vertically using flex-direction!",
    basketCSS: {
      display: "flex",
      flexDirection: "column",
      gap: "1rem",
      height: "100%",
      width: "100%",
    },
    fruitCSS: {
      display: "flex",
      gap: "1rem",
      height: "100%",
      width: "100%",
    },
    missingProps: ["flex-direction:column"],
    maxLines: 1,
    acceptedAnswers: [
      "flex-direction: column;",
      "flex-direction:column;",
      "flex-direction: column",
      "flex-direction:column",
    ],
    fruits: [
      { type: "apple", initialPosition: 1, correctPosition: 1 },
      { type: "banana", initialPosition: 2, correctPosition: 2 },
      { type: "grapes", initialPosition: 3, correctPosition: 3 },
    ],
    baskets: [
      { type: "red", position: 1 },
      { type: "yellow", position: 2 },
      { type: "violet", position: 3 },
    ],
    containerLayout: "simple",
    cssTarget: "container",
  },
  10: {
    instructions:
      "Use flex properties to place the fruits in the correct baskets",
    basketCSS: {
      display: "flex",
      flexDirection: "row-reverse",
      justifyContent: "flex-end",
      gap: "1rem",
      height: "100%",
      width: "100%",
    },
    fruitCSS: {
      display: "flex",
      gap: "1rem",
      height: "100%",
      width: "100%",
    },
    missingProps: ["flex-direction:row-reverse", "justify-content:flex-end"],
    maxLines: 2,
    acceptedAnswers: [
      "flex-direction: row-reverse;\njustify-content: flex-end;",
      "flex-direction:row-reverse;\njustify-content:flex-end;",
      "flex-direction: row-reverse; justify-content: flex-end;",
      "flex-direction:row-reverse; justify-content:flex-end;",
      "justify-content: flex-end;\nflex-direction: row-reverse;",
      "justify-content:flex-end;\nflex-direction:row-reverse;",
      "justify-content: flex-end; flex-direction: row-reverse;",
      "justify-content:flex-end; flex-direction:row-reverse;",
    ],
    fruits: [
      { type: "apple", initialPosition: 1, correctPosition: 3 },
      { type: "banana", initialPosition: 2, correctPosition: 1 },
      { type: "grapes", initialPosition: 3, correctPosition: 2 },
    ],
    baskets: [
      { type: "red", position: 3 },
      { type: "yellow", position: 1 },
      { type: "violet", position: 2 },
    ],
    containerLayout: "simple",
    cssTarget: "container",
  },
  11: {
    instructions:
      "Use flex properties to place the fruits in the correct baskets",
    basketCSS: {
      display: "flex",
      flexDirection: "column",
      justifyContent: "flex-end",
      gap: "1rem",
      height: "100%",
      width: "100%",
    },
    fruitCSS: {
      display: "flex",
      gap: "1rem",
      height: "100%",
      width: "100%",
    },
    missingProps: ["flex-direction:column", "justify-content:flex-end"],
    maxLines: 2,
    acceptedAnswers: [
      "flex-direction: column;\njustify-content: flex-end;",
      "flex-direction:column;\njustify-content:flex-end;",
      "flex-direction: column; justify-content: flex-end;",
      "flex-direction:column; justify-content:flex-end;",
      "justify-content: flex-end;\nflex-direction: column;",
      "justify-content:flex-end;\nflex-direction:column;",
      "justify-content: flex-end; flex-direction: column;",
      "justify-content:flex-end; flex-direction:column;",
    ],
    fruits: [
      { type: "apple", initialPosition: 1, correctPosition: 2 },
      { type: "banana", initialPosition: 2, correctPosition: 3 },
      { type: "grapes", initialPosition: 3, correctPosition: 1 },
    ],
    baskets: [
      { type: "red", position: 2 },
      { type: "yellow", position: 3 },
      { type: "violet", position: 1 },
    ],
    containerLayout: "simple",
    cssTarget: "container",
  },
  12: {
    instructions:
      "Use flex properties to place the fruits in the correct baskets",
    basketCSS: {
      display: "flex",
      flexDirection: "column-reverse",
      justifyContent: "space-between",
      height: "100%",
      width: "100%",
      gap: "1rem",
    },
    fruitCSS: {
      display: "flex",
      gap: "1rem",
      height: "100%",
      width: "100%",
    },
    missingProps: [
      "flex-direction:column-reverse",
      "justify-content:space-between",
    ],
    maxLines: 2,
    acceptedAnswers: [
      "flex-direction: column-reverse;\njustify-content: space-between;",
      "flex-direction:column-reverse;\njustify-content:space-between;",
      "flex-direction: column-reverse; justify-content: space-between;",
      "flex-direction:column-reverse; justify-content:space-between;",
      "justify-content: space-between;\nflex-direction: column-reverse;",
      "justify-content:space-between;\nflex-direction:column-reverse;",
      "justify-content: space-between; flex-direction: column-reverse;",
      "justify-content:space-between; flex-direction:column-reverse;",
    ],
    fruits: [
      { type: "apple", initialPosition: 1, correctPosition: 3 },
      { type: "banana", initialPosition: 2, correctPosition: 1 },
      { type: "grapes", initialPosition: 3, correctPosition: 2 },
    ],
    baskets: [
      { type: "red", position: 3 },
      { type: "yellow", position: 1 },
      { type: "violet", position: 2 },
    ],
    containerLayout: "simple",
    cssTarget: "container",
  },
  13: {
    instructions:
      "Use flex properties to place the fruits in the correct baskets",
    basketCSS: {
      display: "flex",
      flexDirection: "row-reverse",
      justifyContent: "center",
      alignItems: "flex-end",
      gap: "1rem",
      height: "100%",
      width: "100%",
    },
    fruitCSS: {
      display: "flex",
      gap: "1rem",
      height: "100%",
      width: "100%",
    },
    missingProps: [
      "flex-direction:row-reverse",
      "justify-content:center",
      "align-items:flex-end",
    ],
    maxLines: 3,
    acceptedAnswers: [
      "flex-direction: row-reverse;\njustify-content: center;\nalign-items: flex-end;",
      "flex-direction:row-reverse;\njustify-content:center;\nalign-items:flex-end;",
      "flex-direction: row-reverse; justify-content: center; align-items: flex-end;",
      "flex-direction:row-reverse; justify-content:center; align-items:flex-end;",
      "justify-content: center;\nflex-direction: row-reverse;\nalign-items: flex-end;",
      "justify-content:center;\nflex-direction:row-reverse;\nalign-items:flex-end;",
      "justify-content: center; flex-direction: row-reverse; align-items: flex-end;",
      "justify-content:center; flex-direction:row-reverse; align-items:flex-end;",
      "align-items: flex-end;\nflex-direction: row-reverse;\njustify-content: center;",
      "align-items:flex-end;\nflex-direction:row-reverse;\njustify-content:center;",
      "align-items: flex-end; flex-direction: row-reverse; justify-content: center;",
      "align-items:flex-end; flex-direction:row-reverse; justify-content:center;",
    ],
    fruits: [
      { type: "apple", initialPosition: 1, correctPosition: 2 },
      { type: "banana", initialPosition: 2, correctPosition: 3 },
      { type: "grapes", initialPosition: 3, correctPosition: 1 },
    ],
    baskets: [
      { type: "red", position: 2 },
      { type: "yellow", position: 3 },
      { type: "violet", position: 1 },
    ],
    containerLayout: "simple",
    cssTarget: "container",
  },
  14: {
    instructions:
      "Use flex properties to place the fruits in the correct baskets",
    basketCSS: {
      display: "flex",
      flexWrap: "wrap",
      gap: "1rem",
      height: "100%",
      width: "100%",
    },
    fruitCSS: {
      display: "flex",
      gap: "1rem",
      height: "100%",
      width: "100%",
    },
    missingProps: ["flex-wrap:wrap"],
    maxLines: 1,
    acceptedAnswers: [
      "flex-wrap: wrap;",
      "flex-wrap:wrap;",
      "flex-wrap: wrap",
      "flex-wrap:wrap",
    ],
    fruits: [
      { type: "banana", initialPosition: 1, correctPosition: 2 },
      { type: "apple", initialPosition: 1, correctPosition: 2 },
      { type: "apple", initialPosition: 1, correctPosition: 2 },
      { type: "apple", initialPosition: 1, correctPosition: 2 },
      { type: "apple", initialPosition: 1, correctPosition: 2 },
      { type: "apple", initialPosition: 1, correctPosition: 2 },
      { type: "grapes", initialPosition: 3, correctPosition: 1 },
    ],
    baskets: [
      { type: "yellow", position: 2 },
      { type: "red", position: 1 },
      { type: "red", position: 1 },
      { type: "red", position: 1 },
      { type: "red", position: 1 },
      { type: "red", position: 1 },
      { type: "violet", position: 3 },
    ],
    containerLayout: "simple",
    cssTarget: "container",
  },
  15: {
    instructions:
      "Use flex properties to place the fruits in the correct baskets",
    basketCSS: {
      display: "flex",
      flexWrap: "wrap-reverse",
      gap: "1rem",
      height: "100%",
      width: "100%",
    },
    fruitCSS: {
      display: "flex",
      gap: "1rem",
      height: "100%",
      width: "100%",
    },
    missingProps: ["flex-wrap:wrap-reverse"],
    maxLines: 1,
    acceptedAnswers: [
      "flex-wrap: wrap-reverse;",
      "flex-wrap:wrap-reverse;",
      "flex-wrap: wrap-reverse",
      "flex-wrap:wrap-reverse",
    ],
    fruits: [
      { type: "apple", initialPosition: 1, correctPosition: 2 },
      { type: "apple", initialPosition: 1, correctPosition: 2 },
      { type: "apple", initialPosition: 1, correctPosition: 2 },
      { type: "apple", initialPosition: 1, correctPosition: 2 },
      { type: "apple", initialPosition: 1, correctPosition: 2 },
      { type: "banana", initialPosition: 1, correctPosition: 1 },
      { type: "banana", initialPosition: 1, correctPosition: 1 },
      { type: "banana", initialPosition: 1, correctPosition: 1 },
      { type: "banana", initialPosition: 1, correctPosition: 1 },
      { type: "banana", initialPosition: 1, correctPosition: 1 },
      { type: "grapes", initialPosition: 3, correctPosition: 3 },
      { type: "grapes", initialPosition: 3, correctPosition: 3 },
      { type: "grapes", initialPosition: 3, correctPosition: 3 },
      { type: "grapes", initialPosition: 3, correctPosition: 3 },
      { type: "grapes", initialPosition: 3, correctPosition: 3 },
    ],
    baskets: [
      { type: "red", position: 2 },
      { type: "red", position: 2 },
      { type: "red", position: 2 },
      { type: "red", position: 2 },
      { type: "red", position: 2 },
      { type: "yellow", position: 1 },
      { type: "yellow", position: 1 },
      { type: "yellow", position: 1 },
      { type: "yellow", position: 1 },
      { type: "yellow", position: 1 },
      { type: "violet", position: 3 },
      { type: "violet", position: 3 },
      { type: "violet", position: 3 },
      { type: "violet", position: 3 },
      { type: "violet", position: 3 },
    ],
    containerLayout: "simple",
    cssTarget: "container",
  },
  16: {
    instructions:
      "Use flex properties to place the fruits in the correct baskets",
    basketCSS: {
      display: "flex",
      flexFlow: "column wrap",
      gap: "1rem",
      height: "100%",
      width: "100%",
    },
    fruitCSS: {
      display: "flex",
      gap: "1rem",
      height: "100%",
      width: "100%",
    },
    missingProps: ["flex-flow:column wrap"],
    maxLines: 1,
    acceptedAnswers: [
      "flex-flow: column wrap;",
      "flex-flow:column wrap;",
      "flex-flow: column wrap",
      "flex-flow:column wrap",
    ],
    fruits: [
      { type: "apple", initialPosition: 1, correctPosition: 2 },
      { type: "apple", initialPosition: 1, correctPosition: 2 },
      { type: "apple", initialPosition: 1, correctPosition: 2 },
      { type: "apple", initialPosition: 1, correctPosition: 2 },
      { type: "apple", initialPosition: 1, correctPosition: 2 },
      { type: "banana", initialPosition: 1, correctPosition: 1 },
      { type: "banana", initialPosition: 1, correctPosition: 1 },
      { type: "banana", initialPosition: 1, correctPosition: 1 },
      { type: "banana", initialPosition: 1, correctPosition: 1 },
      { type: "banana", initialPosition: 1, correctPosition: 1 },
      { type: "grapes", initialPosition: 3, correctPosition: 3 },
      { type: "grapes", initialPosition: 3, correctPosition: 3 },
      { type: "grapes", initialPosition: 3, correctPosition: 3 },
      { type: "grapes", initialPosition: 3, correctPosition: 3 },
      { type: "grapes", initialPosition: 3, correctPosition: 3 },
    ],
    baskets: [
      { type: "yellow", position: 1 },
      { type: "yellow", position: 1 },
      { type: "yellow", position: 1 },
      { type: "yellow", position: 1 },
      { type: "yellow", position: 1 },
      { type: "red", position: 2 },
      { type: "red", position: 2 },
      { type: "red", position: 2 },
      { type: "red", position: 2 },
      { type: "red", position: 2 },
      { type: "violet", position: 3 },
      { type: "violet", position: 3 },
      { type: "violet", position: 3 },
      { type: "violet", position: 3 },
      { type: "violet", position: 3 },
    ],
    containerLayout: "simple",
    cssTarget: "container",
  },
  17: {
    instructions:
      "Use flex properties to place the fruits in the correct baskets",
    basketCSS: {
      display: "flex",
      flexWrap: "wrap",
      alignContent: "flex-start",
      gap: "1rem",
      height: "100%",
      width: "100%",
    },
    fruitCSS: {
      display: "flex",
      gap: "1rem",
      height: "100%",
      width: "100%",
    },
    missingProps: ["flex-wrap:wrap", "align-content:flex-start"],
    maxLines: 2,
    acceptedAnswers: [
      "flex-wrap: wrap;\nalign-content: flex-start;",
      "flex-wrap:wrap;\nalign-content:flex-start;",
      "flex-wrap: wrap; align-content: flex-start;",
      "flex-wrap: wrap;align-content: flex-start;",
      "flex-wrap:wrap; align-content:flex-start;",
      "align-content: flex-start;\nflex-wrap: wrap;",
      "align-content:flex-start;\nflex-wrap:wrap;",
      "align-content: flex-start; flex-wrap: wrap;",
      "align-content:flex-start; flex-wrap:wrap;",
      "align-content: flex-start;flex-wrap: wrap;",
      "align-content:flex-start;flex-wrap:wrap;",
    ],
    fruits: [
      { type: "apple", initialPosition: 1, correctPosition: 2 },
      { type: "apple", initialPosition: 1, correctPosition: 2 },
      { type: "apple", initialPosition: 1, correctPosition: 2 },
      { type: "apple", initialPosition: 1, correctPosition: 2 },
      { type: "apple", initialPosition: 1, correctPosition: 2 },
      { type: "apple", initialPosition: 1, correctPosition: 2 },
      { type: "apple", initialPosition: 1, correctPosition: 2 },
      { type: "apple", initialPosition: 1, correctPosition: 2 },
    ],
    baskets: [
      { type: "red", position: 2 },
      { type: "red", position: 2 },
      { type: "red", position: 2 },
      { type: "red", position: 2 },
      { type: "red", position: 2 },
      { type: "red", position: 2 },
      { type: "red", position: 2 },
      { type: "red", position: 2 },
    ],
    containerLayout: "simple",
    cssTarget: "container",
  },
};

export const getFlexLevel = (levelNumber) => {
  return flexLevelConfigs[levelNumber] || flexLevelConfigs[1];
};
