export const gridLevelConfigs = {
  1: {
    instructions:
      "Use grid-template-columns to create 3 equal columns for the fruits",
    basketCSS: {
      display: "grid",
      gridTemplateColumns: "1fr 1fr 1fr",
      gap: "1rem",
      width: "100%",
      height: "200px",
    },
    fruitCSS: {
      display: "grid",
      gap: "1rem",
      width: "100%",
      height: "200px",
    },
    missingProps: ["grid-template-columns:1fr 1fr 1fr"],
    maxLines: 1,
    acceptedAnswers: [
      "grid-template-columns: 1fr 1fr 1fr;",
      "grid-template-columns:1fr 1fr 1fr;",
      "grid-template-columns: 1fr 1fr 1fr",
      "grid-template-columns:1fr 1fr 1fr",
      "grid-template-columns: repeat(3, 1fr);",
      "grid-template-columns:repeat(3, 1fr);",
      "grid-template-columns: repeat(3, 1fr)",
      "grid-template-columns:repeat(3, 1fr)",
    ],
    fruits: [
      { type: "apple", initialPosition: 1, correctPosition: 1 },
      { type: "banana", initialPosition: 2, correctPosition: 2 },
      { type: "grapes", initialPosition: 3, correctPosition: 3 },
    ],
    baskets: [
      { type: "red", position: 1 },
      { type: "yellow", position: 2 },
      { type: "violet", position: 3 },
    ],
    containerLayout: "simple",
    cssTarget: "container",
  },
  2: {
    instructions:
      "Use grid-template-columns to create columns with different sizes (2fr 1fr 1fr)",
    basketCSS: {
      display: "grid",
      gridTemplateColumns: "2fr 1fr 1fr",
      gap: "1rem",
      width: "100%",
      height: "200px",
    },
    fruitCSS: {
      display: "grid",
      gap: "1rem",
      width: "100%",
      height: "200px",
    },
    missingProps: ["grid-template-columns:2fr 1fr 1fr"],
    maxLines: 1,
    acceptedAnswers: [
      "grid-template-columns: 2fr 1fr 1fr;",
      "grid-template-columns:2fr 1fr 1fr;",
      "grid-template-columns: 2fr 1fr 1fr",
      "grid-template-columns:2fr 1fr 1fr",
    ],
    fruits: [
      { type: "apple", initialPosition: 1, correctPosition: 1 },
      { type: "banana", initialPosition: 2, correctPosition: 2 },
      { type: "grapes", initialPosition: 3, correctPosition: 3 },
    ],
    baskets: [
      { type: "red", position: 1 },
      { type: "yellow", position: 2 },
      { type: "violet", position: 3 },
    ],
    containerLayout: "simple",
    cssTarget: "container",
  },
  3: {
    instructions:
      "Use grid-template-rows to create 3 rows and arrange fruits vertically",
    basketCSS: {
      display: "grid",
      gridTemplateRows: "1fr 1fr 1fr",
      gap: "1rem",
      width: "200px",
      height: "100%",
    },
    fruitCSS: {
      display: "grid",
      gap: "1rem",
      width: "200px",
      height: "100%",
    },
    missingProps: ["grid-template-rows:1fr 1fr 1fr"],
    maxLines: 1,
    acceptedAnswers: [
      "grid-template-rows: 1fr 1fr 1fr;",
      "grid-template-rows:1fr 1fr 1fr;",
      "grid-template-rows: 1fr 1fr 1fr",
      "grid-template-rows:1fr 1fr 1fr",
      "grid-template-rows: repeat(3, 1fr);",
      "grid-template-rows:repeat(3, 1fr);",
      "grid-template-rows: repeat(3, 1fr)",
      "grid-template-rows:repeat(3, 1fr)",
    ],
    fruits: [
      { type: "apple", initialPosition: 1, correctPosition: 1 },
      { type: "banana", initialPosition: 2, correctPosition: 2 },
      { type: "grapes", initialPosition: 3, correctPosition: 3 },
    ],
    baskets: [
      { type: "red", position: 1 },
      { type: "yellow", position: 2 },
      { type: "violet", position: 3 },
    ],
    containerLayout: "simple",
    cssTarget: "container",
  },
  4: {
    instructions:
      "Use justify-items to center all items horizontally in their grid cells",
    basketCSS: {
      display: "grid",
      gridTemplateColumns: "1fr 1fr 1fr",
      justifyItems: "center",
      gap: "1rem",
      width: "100%",
      height: "200px",
    },
    fruitCSS: {
      display: "grid",
      gridTemplateColumns: "1fr 1fr 1fr",
      gap: "1rem",
      width: "100%",
      height: "200px",
    },
    missingProps: ["justify-items:center"],
    maxLines: 1,
    acceptedAnswers: [
      "justify-items: center;",
      "justify-items:center;",
      "justify-items: center",
      "justify-items:center",
    ],
    fruits: [
      { type: "apple", initialPosition: 1, correctPosition: 1 },
      { type: "banana", initialPosition: 2, correctPosition: 2 },
      { type: "grapes", initialPosition: 3, correctPosition: 3 },
    ],
    baskets: [
      { type: "red", position: 1 },
      { type: "yellow", position: 2 },
      { type: "violet", position: 3 },
    ],
    containerLayout: "simple",
    cssTarget: "container",
  },
  5: {
    instructions:
      "Use both justify-items and align-items to center items perfectly in their cells",
    basketCSS: {
      display: "grid",
      gridTemplateColumns: "1fr 1fr 1fr",
      justifyItems: "center",
      alignItems: "center",
      gap: "1rem",
      width: "100%",
      height: "300px",
    },
    fruitCSS: {
      display: "grid",
      gridTemplateColumns: "1fr 1fr 1fr",
      gap: "1rem",
      width: "100%",
      height: "300px",
    },
    missingProps: ["justify-items:center", "align-items:center"],
    maxLines: 2,
    acceptedAnswers: [
      "justify-items: center;\nalign-items: center;",
      "justify-items:center;\nalign-items:center;",
      "justify-items: center; align-items: center;",
      "justify-items:center; align-items:center;",
      "align-items: center;\njustify-items: center;",
      "align-items:center;\njustify-items:center;",
      "align-items: center; justify-items: center;",
      "align-items:center; justify-items:center;",
    ],
    fruits: [
      { type: "apple", initialPosition: 1, correctPosition: 1 },
      { type: "banana", initialPosition: 2, correctPosition: 2 },
      { type: "grapes", initialPosition: 3, correctPosition: 3 },
    ],
    baskets: [
      { type: "red", position: 1 },
      { type: "yellow", position: 2 },
      { type: "violet", position: 3 },
    ],
    containerLayout: "simple",
    cssTarget: "container",
  },
  6: {
    instructions:
      "Use justify-content to center the entire grid horizontally in the container",
    basketCSS: {
      display: "grid",
      gridTemplateColumns: "100px 100px 100px",
      justifyContent: "center",
      gap: "1rem",
      width: "100%",
      height: "200px",
    },
    fruitCSS: {
      display: "grid",
      gridTemplateColumns: "100px 100px 100px",
      gap: "1rem",
      width: "100%",
      height: "200px",
    },
    missingProps: ["justify-content:center"],
    maxLines: 1,
    acceptedAnswers: [
      "justify-content: center;",
      "justify-content:center;",
      "justify-content: center",
      "justify-content:center",
    ],
    fruits: [
      { type: "apple", initialPosition: 1, correctPosition: 1 },
      { type: "banana", initialPosition: 2, correctPosition: 2 },
      { type: "grapes", initialPosition: 3, correctPosition: 3 },
    ],
    baskets: [
      { type: "red", position: 1 },
      { type: "yellow", position: 2 },
      { type: "violet", position: 3 },
    ],
    containerLayout: "simple",
    cssTarget: "container",
  },
  7: {
    instructions:
      "Use grid-auto-flow to make items flow in columns instead of rows",
    basketCSS: {
      display: "grid",
      gridTemplateRows: "1fr 1fr",
      gridAutoFlow: "column",
      gap: "1rem",
      width: "100%",
      height: "100%",
    },
    fruitCSS: {
      display: "grid",
      gridTemplateRows: "1fr 1fr",
      gap: "1rem",
      width: "100%",
      height: "100%",
    },
    missingProps: ["grid-auto-flow:column"],
    maxLines: 1,
    acceptedAnswers: [
      "grid-auto-flow: column;",
      "grid-auto-flow:column;",
      "grid-auto-flow: column",
      "grid-auto-flow:column",
    ],
    fruits: [
      { type: "apple", initialPosition: 1, correctPosition: 1 },
      { type: "banana", initialPosition: 2, correctPosition: 2 },
      { type: "grapes", initialPosition: 3, correctPosition: 3 },
      { type: "apple", initialPosition: 4, correctPosition: 4 },
    ],
    baskets: [
      { type: "red", position: 1 },
      { type: "yellow", position: 2 },
      { type: "violet", position: 3 },
      { type: "red", position: 4 },
    ],
    containerLayout: "simple",
    cssTarget: "container",
  },
  8: {
    instructions:
      "Use grid-template-areas to create named grid areas for fruit placement",
    basketCSS: {
      display: "grid",
      gridTemplateAreas: '"red yellow" "red violet"',
      gridTemplateColumns: "1fr 1fr",
      gridTemplateRows: "1fr 1fr",
      gap: "1rem",
      width: "100%",
      height: "100%",
    },
    fruitCSS: {
      display: "grid",
      gridTemplateColumns: "1fr 1fr",
      gridTemplateRows: "1fr 1fr",
      gap: "1rem",
      width: "100%",
      height: "100%",
    },
    missingProps: ['grid-template-areas:"red yellow" "red violet"'],
    maxLines: 1,
    acceptedAnswers: [
      'grid-template-areas: "red yellow" "red violet";',
      'grid-template-areas:"red yellow" "red violet";',
      'grid-template-areas: "red yellow" "red violet"',
      'grid-template-areas:"red yellow" "red violet"',
    ],
    fruits: [
      {
        type: "apple",
        initialPosition: 1,
        correctPosition: 1,
        gridArea: "red",
      },
      {
        type: "banana",
        initialPosition: 2,
        correctPosition: 2,
        gridArea: "yellow",
      },
      {
        type: "grapes",
        initialPosition: 3,
        correctPosition: 3,
        gridArea: "violet",
      },
    ],
    baskets: [
      { type: "red", position: 1, gridArea: "red" },
      { type: "yellow", position: 2, gridArea: "yellow" },
      { type: "violet", position: 3, gridArea: "violet" },
    ],
    containerLayout: "simple",
    cssTarget: "container",
  },
  9: {
    instructions:
      "Use grid-template-columns with minmax to create responsive columns",
    basketCSS: {
      display: "grid",
      gridTemplateColumns: "repeat(3, minmax(100px, 1fr))",
      gap: "1rem",
      width: "100%",
      height: "200px",
    },
    fruitCSS: {
      display: "grid",
      gap: "1rem",
      width: "100%",
      height: "200px",
    },
    missingProps: ["grid-template-columns:repeat(3, minmax(100px, 1fr))"],
    maxLines: 1,
    acceptedAnswers: [
      "grid-template-columns: repeat(3, minmax(100px, 1fr));",
      "grid-template-columns:repeat(3, minmax(100px, 1fr));",
      "grid-template-columns: repeat(3, minmax(100px, 1fr))",
      "grid-template-columns:repeat(3, minmax(100px, 1fr))",
      "grid-template-columns: minmax(100px, 1fr) minmax(100px, 1fr) minmax(100px, 1fr);",
      "grid-template-columns:minmax(100px, 1fr) minmax(100px, 1fr) minmax(100px, 1fr);",
      "grid-template-columns: minmax(100px, 1fr) minmax(100px, 1fr) minmax(100px, 1fr)",
      "grid-template-columns:minmax(100px, 1fr) minmax(100px, 1fr) minmax(100px, 1fr)",
    ],
    fruits: [
      { type: "apple", initialPosition: 1, correctPosition: 1 },
      { type: "banana", initialPosition: 2, correctPosition: 2 },
      { type: "grapes", initialPosition: 3, correctPosition: 3 },
    ],
    baskets: [
      { type: "red", position: 1 },
      { type: "yellow", position: 2 },
      { type: "violet", position: 3 },
    ],
    containerLayout: "simple",
    cssTarget: "container",
  },
  10: {
    instructions:
      "Master level: Create a complex grid layout with multiple properties",
    basketCSS: {
      display: "grid",
      gridTemplateColumns: "2fr 1fr 2fr",
      gridAutoFlow: "dense",
      justifyItems: "center",
      alignItems: "center",
      justifyContent: "space-around",
      gap: "1.5rem",
      width: "100%",
      height: "300px",
    },
    fruitCSS: {
      display: "grid",
      gap: "1.5rem",
      width: "100%",
      height: "300px",
    },
    missingProps: [
      "grid-template-columns:2fr 1fr 2fr",
      "grid-auto-flow:dense",
      "justify-items:center",
      "align-items:center",
      "justify-content:space-around",
    ],
    maxLines: 5,
    acceptedAnswers: [
      "grid-template-columns: 2fr 1fr 2fr;\ngrid-auto-flow: dense;\njustify-items: center;\nalign-items: center;\njustify-content: space-around;",
      "grid-template-columns:2fr 1fr 2fr;\ngrid-auto-flow:dense;\njustify-items:center;\nalign-items:center;\njustify-content:space-around;",
      "grid-template-columns: 2fr 1fr 2fr; grid-auto-flow: dense; justify-items: center; align-items: center; justify-content: space-around;",
      "grid-template-columns:2fr 1fr 2fr; grid-auto-flow:dense; justify-items:center; align-items:center; justify-content:space-around;",
    ],
    fruits: [
      { type: "apple", initialPosition: 1, correctPosition: 1 },
      { type: "banana", initialPosition: 2, correctPosition: 2 },
      { type: "grapes", initialPosition: 3, correctPosition: 3 },
      { type: "apple", initialPosition: 4, correctPosition: 4 },
      { type: "banana", initialPosition: 5, correctPosition: 5 },
    ],
    baskets: [
      { type: "red", position: 1 },
      { type: "yellow", position: 2 },
      { type: "violet", position: 3 },
      { type: "red", position: 4 },
      { type: "yellow", position: 5 },
    ],
    containerLayout: "simple",
    cssTarget: "container",
  },
};

export const getLevel = (levelNumber) => {
  return gridLevelConfigs[levelNumber] || gridLevelConfigs[1];
};
